epoqueart/epoqueart/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from .sitemaps import StaticViewSitemap

from main import views

handler400 = "main.views.handler400"
handler401 = "main.views.handler401"
handler403 = "main.views.handler403"
handler404 = "main.views.handler404"
handler500 = "main.views.handler500"

sitemaps = {
    'sitemaps': StaticViewSitemap
}

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("artists/", views.artists, name="artists"),
    path("artist/<slug:slug>/", views.artist, name="artist"),
    path("collection", views.collection, name="collection"),
    path("interiors/", views.interior, name="interior"),
    path("on demand/", views.on_demand, name="on_demand"),
    path("gallery/", views.gallery, name="gallery"),
    path("api/gallery/search", views.gallery_search_api, name="gallery_search_api"),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("logout/", views.logout_view, name="user_logout"),
    # Error handlers
    path('400/', views.handler400),
    path('401/', views.handler401),
    path('403/', views.handler403),
    path('404/', views.handler404),
    path('500/', views.handler500),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

epoqueart/main/models.py
import datetime
import os
from django.db import models
from django.forms import ValidationError
from accounts.models import CustomUser
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.utils import timezone
from uuid import uuid4


def wrapper(instance, filename):
    ext = filename.split(".")[-1]
    return "images/content/{}.{}".format(uuid4().hex, ext)


class Country(models.Model):
    country = models.CharField(_("Country"), max_length=255)

    class Meta:
        verbose_name = _("Country")
        verbose_name_plural = _("Countries")

    def __str__(self):
        return self.country


class City(models.Model):
    city_name = models.CharField(_("City name"), max_length=255)
    postal_code = models.CharField(_("Postal code"), max_length=32)
    country = models.ForeignKey(
        Country, verbose_name=_("Country"), on_delete=models.PROTECT
    )

    class Meta:
        verbose_name = _("City")
        verbose_name_plural = _("Cities")

    def __str__(self):
        return self.city_name


class Currency(models.Model):
    country = models.ForeignKey(
        Country, on_delete=models.PROTECT, verbose_name=_("Country")
    )
    currency_name = models.CharField(_("Currency name"), max_length=255)
    currency_short = models.CharField(
        _("Currency short name"),
        max_length=10,
        help_text=_("Currency short name, e.g. 'EUR'"),
    )
    currency_symbol = models.CharField(
        _("Currency symbol"), max_length=3, help_text="Currency symbol, e.g. '€'"
    )

    class Meta:
        verbose_name = _("Currency")
        verbose_name_plural = _("Currencies")

    def __str__(self):
        return self.currency_name


class Gallery(models.Model):
    gallery_name = models.CharField(
        _("Gallery name"), max_length=255, help_text=_("Name of physical gallery.")
    )
    gallery_address = models.CharField(_("Gallery address"), max_length=512)
    gallery_description = models.TextField(
        _("Gallery description"), max_length=512, blank=True
    )
    city = models.ForeignKey(City, verbose_name=_("City"), on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.gallery_name} - {self.gallery_address}"

    class Meta:
        verbose_name = _("Gallery")
        verbose_name_plural = _("Galleries")


class Author(models.Model):
    preview_image = models.ImageField(
        _("Author preview image"),
        upload_to=wrapper,
        help_text=_("This image will be shown at author preview page."),
    )
    image = models.ImageField(
        _("Author image"),
        upload_to=wrapper,
        help_text=_("This image will be shown at author page."),
    )
    name = models.CharField(_("Full name"), max_length=255, unique=True)
    qualification = models.CharField(
        _("Qualification"),
        max_length=255,
        help_text=_("Qualification of author, e.g. 'Surrealist master'"),
    )
    description = models.TextField(_("Description"))
    slug = models.SlugField(_("Slug"), unique=True, editable=False, null=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = _("Author")
        verbose_name_plural = _("Authors")

    def get_personal_url(self):
        return self.slug or slugify(self.name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Author, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if os.path.isfile(self.preview_image.path):
            os.remove(self.preview_image.path)

        if os.path.isfile(self.image.path):
            os.remove(self.image.path)

        super(Author, self).delete(*args, **kwargs)


class Artwork_Type(models.Model):
    artwork_type_name = models.CharField(
        _("Type"),
        max_length=255,
        unique=True,
        help_text=_("Type of artwork, e.g. 'Bust'"),
    )

    def __str__(self):
        return self.artwork_type_name

    class Meta:
        verbose_name = _("Artwork Type")
        verbose_name_plural = _("Artwork Type")


class Artwork_Status(models.Model):
    artwork_status_name = models.CharField(
        _("Status"),
        max_length=255,
        unique=True,
        help_text=_("Status of artwork, e.g. 'Sold' or 'Reserved'"),
    )
    artwork_is_available = models.BooleanField(
        _("Is Available"),
        default=True,
        help_text=_("Determines if artwork is available to customers."),
    )

    def __str__(self):
        return self.artwork_status_name

    class Meta:
        verbose_name = _("Artwork Status")
        verbose_name_plural = _("Artwork Status")


class Artwork(models.Model):
    title = models.CharField(
        _("Title"), max_length=255, help_text=_("Title of artwork.")
    )
    author = models.ForeignKey(
        Author,
        on_delete=models.PROTECT,
        verbose_name=_("Author"),
        help_text=_("Author of artwork."),
    )
    date = models.DateField(
        _("Date"), null=True, help_text=_("Date of creation of artwork.")
    )

    image = models.ImageField(
        _("Image"), upload_to=wrapper, help_text=_("High-res image of artwork.")
    )

    description = models.TextField(
        _("Description"), help_text=_("Description of artwork.")
    )

    type = models.ForeignKey(
        Artwork_Type,
        on_delete=models.PROTECT,
        verbose_name=_("Type"),
        help_text=_("Type of artwork."),
    )

    width = models.PositiveIntegerField(
        _("Width"), help_text=_("Determines width of artwork."), null=True
    )

    height = models.PositiveIntegerField(
        _("Height"), help_text=_("Determines height of artwork."), null=True
    )

    MEASURE_CHOICES = (
        ("Inch", _("Inch")),
        ("Centimeters", _("Centimeters")),
    )

    measure = models.CharField(
        _("Measure unit"), choices=MEASURE_CHOICES, max_length=24
    )
    materials = models.CharField(
        _("Materials"), max_length=255, null=True, help_text=_("Materials of artwork.")
    )

    price = models.PositiveIntegerField(_("Price"), help_text=_("Price of artwork."))

    currency = models.ForeignKey(
        Currency,
        verbose_name=("Currency"),
        on_delete=models.PROTECT,
        help_text=_("Payment currency."),
    )

    is_nft_linked = models.BooleanField(
        _("Is NFT token linked?"),
        default=False,
        help_text=_("Determines if the token is linked to a physical object."),
    )

    location = models.ForeignKey(
        Gallery,
        verbose_name=_("Location"),
        on_delete=models.PROTECT,
        help_text=_("Physical location of artwork."),
    )
    status = models.ForeignKey(
        Artwork_Status,
        on_delete=models.PROTECT,
        verbose_name=_("Status"),
        help_text=_("Status of artwork."),
    )

    def get_size_cm(self):
        if self.measure == "Inch":
            return (int(round(self.width * 2.54, 0)), int(round(self.height * 2.54, 0)))
        if self.measure == "Centimeters":
            return (self.width, self.height)

    def get_size_inch(self):
        if self.measure == "Centimeters":
            return (int(round(self.width / 2.54, 0)), int(round(self.height / 2.54, 0)))
        if self.measure == "Inch":
            return (self.width, self.height)

    def get_personal_url(self):
        return self.slug or slugify(self.name)

    def save(self, *args, **kwargs):
        if self.date > timezone.now().date():
            raise ValidationError("The date cannot be in the future!")
        super(Artwork, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if os.path.isfile(self.image.path):
            os.remove(self.image.path)

        super(Artwork, self).delete(*args, **kwargs)

    def __str__(self):
        return f"{self.author.name} | {self.title}"

    class Meta:
        verbose_name = _("Artwork")
        verbose_name_plural = _("Artworks")


class Event(models.Model):

    event_name = models.CharField(
        _("Title"), max_length=255, help_text="Name of event.", unique=True
    )
    event_description = models.TextField(_("Content"), help_text="Description")
    date = models.DateField(_("Date"), help_text="Date of event")
    image = models.ImageField(
        _("Event preview"), help_text=_("Preview image for event"), upload_to=wrapper
    )

    location = models.ForeignKey(
        Gallery,
        verbose_name=_("Location"),
        on_delete=models.PROTECT,
        help_text=_("Location of event."),
    )

    author = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, verbose_name=_("Author account")
    )
    slug = models.SlugField(_("Slug"), unique=True, editable=False, null=True)

    class Meta:
        ordering = ["-date"]
        verbose_name = "Event"
        verbose_name_plural = "Events"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.event_name)
        super(Event, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if os.path.isfile(self.image.path):
            os.remove(self.image.path)

        super(Event, self).delete(*args, **kwargs)

    def __str__(self):
        return self.event_name

epoqueart/templates/components/artist/artist-header.html
{% load compress %}
{% load static %}

{% compress css inline %}
<style lang="scss" type="text/x-scss">
.artists-header {
    display: inline;
}
</style>
{% endcompress %}

<section class="artists-section-title">Artist | {{ artist.name|safe }}</section>
<section class="artists-section-subtitle"><span>Discover your next work of art. To search by artist, collection and size visit <a href="{% url 'gallery' %}" class="section-integrated_link">NetGallery</a> page.</span></section>

epoqueart/templates/components/artist/artist-info.html
{% load compress %}
{% load static %}

{% compress css inline %}
<style lang="scss" type="text/x-scss">
section.artist-info {
    position: relative;
    display: flex;
    flex-direction: column;
    gap: 20px;

    div.artist-image { 
        position: relative;
        img {
            height: 400px;
            width: 100%;
            overflow: hidden;
            object-fit: cover;
        }
        div.artist-sign {
            display: flex;
            flex-direction: column;

            padding: 12px;
            position: absolute;
            left: 0;
            bottom: 0;

            span.artist-name {
                color: #fff;
                font-weight: 300;
                font-size: calc(0.75em + 5vmin);
            }

            span.artist-qualification {
                color: #fff;
                font-weight: 200;
                font-size: calc(0.75em + 3vmin);
            }
        }
    }
    div.artist-description {
        max-width: 1000px;
        margin: 0 auto;
    }
}
</style>
{% endcompress %}
<section class="artist-info">
    <div class="artist-image">
        <img src="{{ artist.image.url }}" alt="Artist Image">
        <div class="artist-sign">
            <span class="artist-name">{{ artist.name|safe }}</span>
            <span class="artist-qualification">{{ artist.qualification|safe }}</span>
        </div>
    </div>
    <div class="artist-description">
        {{ artist.description|safe }}
    </div>
</section>

epoqueart/templates/components/artist/artist-portfolio.html
{% load compress %}
{% load static %}

{% compress css inline %}
<style lang="scss" type="text/x-scss">
    section.artist-portfolio {
        margin: 20px 0;
        display: flex;
        flex-wrap: wrap;
        flex-direction: row;
        align-items: center;
        justify-content: center;
        gap: 20px;

        div.artist-portfolio__item {
            display: flex;
            flex-direction: column;
            gap: 10px;

            div.artist-portfolio__image {
                position: relative;
                flex: 50%;
                background: #ebebeb;

                min-width: 300px;
                height: 300px;
                
                display: flex;
                align-items: center;
                justify-content: center;

                img {
                    width: 70%;
                    min-width: 300px;
                    padding: 10px;
                    height: 300px;
                    object-fit: contain;
                }

                a.artist-portfolio__view-netgallery {
                    position: absolute;
                    top: 5px;
                    right: 5px;
                    font-size: 1.2em;
                    font-weight: 500;
                    text-align: center;
                    transition: all .3s ease-in-out;
                    border-radius: .2em;

                    i {
                        padding: 5px;
                    }
                }
            }

            div.artist-portfolio__image-details {
                position: relative;
                display: flex;

                div.artist-portfolio__image-details-text {
                    display: flex;
                    flex-direction: column;
                    width: 100%;

                    span.artist-portfolio__image-title {
                        font-size: 1.2em;
                        font-weight: 500;
                    }

                    a.artist-portfolio__download-image {
                        flex: 0;
                        font-size: 1.2em;
                        font-weight: 500;
                        text-align: center;
                        transition: all .3s ease-in-out;
                        border-radius: .2em;

                        &:hover {
                            color: #fff;
                            background-color: #000;
                        }

                        i {
                            padding: 5px;
                        }
                    }

                    span.artist-portfolio__image-subtitle {
                        font-size: .9em;
                        font-weight: 300;
                    }
                }
            }
        }
    }
</style>
{% endcompress %}
{% if artist.artwork_set.all|length > 0 %}
<section class="artist-portfolio">
    {% for artwork in artist.artwork_set.all %}
            {% if artwork.status.artwork_is_available %}
            <div class="artist-portfolio__item">
                <div class="artist-portfolio__image">
                    <img loading="lazy" src="{{ artwork.image.url }}" alt="Artwork Image">
                    <a class="artist-portfolio__view-netgallery" href="{% url 'gallery' %}?aid={{ artwork.id }}"><i class="bi bi-heart"></i></a>
                </div>
                <div class="artist-portfolio__image-details">
                    <div class="artist-portfolio__image-details-text">
                        <div class="d-flex justify-content-between">
                            <span class="artist-portfolio__image-title">{{ artwork.title }}</span>
                            <a class="artist-portfolio__download-image" href="{{ artwork.image.url }}" download="{{ artwork.image.filename }}"><i class="bi bi-download"></i></a>
                        </div>

                        <span class="artist-portfolio__image-subtitle">{{ artwork.author.name }} | {{ artwork.materials }} {% if artwork.is_nft_linked %}| Mixed media artwork{% endif %}</span>
                        <span class="artist-portfolio__image-subtitle">{{ artwork.get_size_cm|join:"x" }} cm | {{ artwork.get_size_inch|join:"x" }} in</span>
                    </div>
                </div>
            </div> 
            {% endif %}
    {% endfor %}
</section>
{% compress js inline %}
<script>
    (function($) {
        $('a.artist-portfolio__view-netgallery').hover(function () {
            $(this).children('i').addClass('bi-heart-fill');
            $(this).children('i').removeClass('bi-heart');
        }, function () {
            $(this).children('i').removeClass('bi-heart-fill');
            $(this).children('i').addClass('bi-heart');
        });
    })(jQuery);
</script>
{% endcompress %}
{% endif %}